# Generated by Django 4.2.11 on 2024-03-30 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_manager_employee_alter_employeeshift_employee_and_more'),
        ('accounts', '0004_manager_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='account',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
