# Generated by Django 4.2.11 on 2024-03-31 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_manager_employee_alter_employeeshift_employee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='employeeshift',
            options={'verbose_name': 'Employee shift', 'verbose_name_plural': 'Employee shifts'},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'verbose_name': 'Manager', 'verbose_name_plural': 'Managers'},
        ),
        migrations.AlterModelOptions(
            name='managershift',
            options={'verbose_name': 'Manager shift', 'verbose_name_plural': 'Manager shifts'},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'verbose_name': 'Shift', 'verbose_name_plural': 'Shifts'},
        ),
        migrations.AlterModelOptions(
            name='weekday',
            options={'verbose_name': 'Week day', 'verbose_name_plural': 'Week days'},
        ),
        migrations.AlterModelOptions(
            name='workday',
            options={'verbose_name': 'Workday', 'verbose_name_plural': 'Workdays'},
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
        migrations.AlterModelTable(
            name='employeeshift',
            table='employee_shifts',
        ),
        migrations.AlterModelTable(
            name='manager',
            table='managers',
        ),
        migrations.AlterModelTable(
            name='managershift',
            table='manager_shifts',
        ),
        migrations.AlterModelTable(
            name='shift',
            table='shifts',
        ),
        migrations.AlterModelTable(
            name='weekday',
            table='week_days',
        ),
        migrations.AlterModelTable(
            name='workday',
            table='workday',
        ),
    ]
