# Generated by Django 4.2.11 on 2024-10-15 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0005_alter_manager_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.workday')),
            ],
            options={
                'verbose_name': 'Availability',
                'verbose_name_plural': 'Availabilities',
                'db_table': 'availabilities',
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shift Assignment',
                'verbose_name_plural': 'Shift Assignments',
                'db_table': 'shift_assignments',
            },
        ),
        migrations.CreateModel(
            name='ShiftSwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requesting_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_swaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shift Swap Request',
                'verbose_name_plural': 'Shift Swap Requests',
                'db_table': 'shift_swap_requests',
            },
        ),
        migrations.RemoveField(
            model_name='employeeshift',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeeshift',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='manageravailability',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='manageravailability',
            name='workday',
        ),
        migrations.RemoveField(
            model_name='managershift',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='managershift',
            name='shift',
        ),
        migrations.AddField(
            model_name='shift',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'Accepted'), ('WAITING', 'Waiting for Accept')], default='WAITING', max_length=20),
        ),
        migrations.DeleteModel(
            name='EmployeeAvailability',
        ),
        migrations.DeleteModel(
            name='EmployeeShift',
        ),
        migrations.DeleteModel(
            name='ManagerAvailability',
        ),
        migrations.DeleteModel(
            name='ManagerShift',
        ),
        migrations.AddField(
            model_name='shiftswaprequest',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.shift'),
        ),
        migrations.AddField(
            model_name='shiftswaprequest',
            name='target_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_targets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.shift'),
        ),
    ]
