# Generated by Django 4.2.11 on 2024-10-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_availability_shiftassignment_shiftswaprequest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='account',
        ),
        migrations.AddField(
            model_name='shiftswaprequest',
            name='target_employee_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shiftswaprequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('EMPLOYEE_APPROVED', 'Employee Approved'), ('MANAGER_APPROVED', 'Manager Approved'), ('DECLINED', 'Declined')], default='PENDING', max_length=20),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
