# Generated by Django 4.2.11 on 2024-10-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0007_remove_manager_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='status',
        ),
        migrations.AlterField(
            model_name='weekday',
            name='day_name',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=50),
        ),
    ]
