# Generated by Django 4.2.11 on 2024-11-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0008_remove_shift_status_alter_weekday_day_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
