# Generated by Django 4.2.11 on 2024-12-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0010_alter_availability_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='is_enrolment_open',
            field=models.BooleanField(default=True),
        ),
    ]
